apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - name: internal
    port: 9092
    targetPort: 9092
  - name: external
    port: 9094
    targetPort: 9094
  clusterIP: None
  selector:
    app: kafka 