apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: web
  selector:
    app: airflow
    component: webserver
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-scheduler
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 8793
    targetPort: 8793
    protocol: TCP
    name: scheduler
  selector:
    app: airflow
    component: scheduler 