apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
  - name: rpc
    port: 6123
  - name: ui
    port: 8081
  selector:
    app: flink
    component: jobmanager 