apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: kafka-ui 